project_id = "babohldgbyiltrixrcwe"

[functions.check-mysql-connection]
verify_jwt = false

[functions.setup-first-admin]
verify_jwt = false

[functions.r2-upload]
verify_jwt = false

[functions.r2-delete]
verify_jwt = false

[functions.r2-get-url]
verify_jwt = false

[functions.test-r2-url]
verify_jwt = false