// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-reviews.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Supabase publishable key is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("Authenticated caller required");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-reviews.ts
var list_reviews_default = defineTool({
  name: "list_reviews",
  title: "Bewertungen auflisten",
  description: "Listet die neuesten Kundenbewertungen, optional gefiltert nach Stadt, Kategorie oder Status.",
  inputSchema: {
    city: z.string().optional().describe("Stadt (Teil\xFCbereinstimmung)"),
    product_category: z.string().optional().describe("Produktkategorie, z.B. Kaminofen"),
    status: z.enum(["draft", "published", "pending"]).optional(),
    limit: z.number().int().min(1).max(100).optional().describe("Anzahl (Standard 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, product_category, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("reviews").select("id, slug, status, city, product_category, average_rating, installation_date, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (city) q = q.ilike("city", `%${city}%`);
    if (product_category) q = q.eq("product_category", product_category);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const reviews = (data ?? []).map((r) => ({
      id: r.id,
      slug: r.slug,
      status: r.status,
      city: r.city,
      product_category: r.product_category,
      average_rating: r.average_rating,
      installation_date: r.installation_date,
      created_at: r.created_at
    }));
    return { content: [{ type: "text", text: JSON.stringify(reviews) }], structuredContent: { reviews } };
  }
});

// src/lib/mcp/tools/get-review.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_review_default = defineTool2({
  name: "get_review",
  title: "Bewertung abrufen",
  description: "Ruft eine einzelne Bewertung mit Details per ID oder Slug ab.",
  inputSchema: {
    id: z2.string().optional().describe("UUID der Bewertung"),
    slug: z2.string().optional().describe("URL-Slug der Bewertung")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, slug }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    if (!id && !slug) return { content: [{ type: "text", text: "id oder slug angeben" }], isError: true };
    let q = supabaseForUser(ctx).from("reviews").select("id, slug, status, city, product_category, average_rating, customer_comment, description_seo, installation_date, before_image_url, after_image_url");
    q = id ? q.eq("id", id) : q.eq("slug", slug);
    const { data, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Nicht gefunden" }], isError: true };
    const review = {
      id: data.id,
      slug: data.slug,
      status: data.status,
      city: data.city,
      product_category: data.product_category,
      average_rating: data.average_rating,
      customer_comment: data.customer_comment,
      description_seo: data.description_seo,
      installation_date: data.installation_date,
      before_image_url: data.before_image_url,
      after_image_url: data.after_image_url
    };
    return { content: [{ type: "text", text: JSON.stringify(review) }], structuredContent: { review } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "babohldgbyiltrixrcwe";
var mcp_default = defineMcp({
  name: "rate-review-kd",
  title: "rate-review-kd",
  version: "0.1.0",
  instructions: "Tools f\xFCr das Bewertungssystem von Der Kamindoktor. Nutze `list_reviews` zum Durchsuchen und `get_review` f\xFCr Details.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_reviews_default, get_review_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
